service: serverless-kinesis-streams

package:
  artifact: package.zip
provider:
  name: aws
  runtime: python2.7
  stage: ${env:ENV}
  region: ${env:AWS_REGION}
  iamRoleStatements:
      - Effect: "Allow"
        Resource: ${env:AWS_KINESIS_ARN}
        Action:
          - "kinesis:GetRecords"
          - "kinesis:GetShardIterator"
          - "kinesis:DescribeStream"
          - "kinesis:ListStreams"
          - "kinesis:PutRecord"
          - "kinesis:PutRecords"
functions:
  publisher:
    handler: handler.DataPublisher
    environment:
      AWS_KINESIS_NAME: ${env:AWS_KINESIS_NAME}
  logger:
    handler: handler.DataLogger
    events:
      - stream: ${env:AWS_KINESIS_ARN}