version: '3'
services:
  golang:
    image: amaysim/golang:1.8.3
    env_file: .env
    volumes:
      - ${GOPATH}/src:/go/src
  go-shim:
    image: eawsy/aws-lambda-go-shim:latest
    env_file: .env
    volumes:
      - .:/build
    working_dir: /build
  serverless:
    image: amaysim/aws-serverless:1.13.0
    env_file: .env
    volumes:
      - .:/build
    working_dir: /build
