[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

# [[constraint]]
#   branch = "master"
#   name = "github.com/yunspace/serverless-golang"

[[constraint]]
  branch = "master"
  name = "github.com/guregu/dynamo"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  branch = "master"
  name = "github.com/nzoschke/gofaas"


