version: '3'
services:
  golang:
    image: golang:1.8
    env_file: .env
    volumes:
      - .:/build
      - $GOPATH:/go
    working_dir: /build
  go-shim:
    image: eawsy/aws-lambda-go-shim:latest
    env_file: .env
    volumes:
      - .:/build
      - $GOPATH:/go
    working_dir: /build
  serverless:
    image: amaysim/aws-serverless:1.13.0
    env_file: .env
    volumes:
      - .:/build
    working_dir: /build
